### PR TITLE
css changes

### PR DESCRIPTION
**Pull request by vinayakt3**
insta page more beautiful

### CODE REVIEW

**Comment by lapak10** [comment]
@imrokin i find this lil change good to go...please review it once... if its good .... we can merge

**Comment by imrokin** [comment]
Bit bsy .. Will review the changes and do the need full.

**Comment by imrokin** [comment]
@vinayak please dont make changes in fw7.css  paste your changes in myapp.css

**Comment by lapak10** [comment]
@imrokin why you merged this??? we need to put that code in some extra file..not in the framework7.css file

**Comment by vinayakt3** [comment]
He has not merged framework7.css he has only merged myapp.css

Thanks and Regards:
* <http://www.freelancer.com/u/vinayakt3.html>*
<http://freelancer.com/u/vinayakt3.html>
Vinayak Tripathi

Web Designer, Graphics Designer, Software developer and Testing

*P: +91 99 99 710715 ,  +91 88 26 154383*

*E: vtripathi58@gmail.com <vtripathi58@gmail.com>*

*A: Delhi-NCR, India*



*9415913402[image: http://freelancer.com/u/vinayakt3.html]
<http://freelancer.com/u/vinayakt3.html>   [image:
http://facebook.com/vinayakt3] <http://facebook.com/vinayakt3>    **[image:
http://twitter.com/vtripathi58]* <http://twitter.com/vtripathi58>

*  [image: https://plus.google.com/u/0/117955603379943063526]
<https://plus.google.com/u/0/117955603379943063526>   [image:
https://www.linkedin.com/profile/view?id=AAIAABfdTP8BC-4rtBEHgTGcDEMzQd2O5enWEoM&trk=nav_responsive_tab_profile_pic]
<https://in.linkedin.com/in/vinayak-tripathi-a7b104b2>*
This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify me and delete the
e-mail from your inbox.

**Comment by lapak10** [comment]
@vinayakt3  you can check it here... in [this commit](https://github.com/imrokin/All-Pilot-Union-App-CrossPlatform/commit/d5d19e85ff11e496ffc6076826be84bae71cd0df) 
that he has changed 2 files both myapp.css and framework7.css

**Pull request merged**
